#!/usr/bin/env python3
"""
Derive Polymarket API credentials from a wallet private key.

The CLOB API requires derived API credentials (key, secret, passphrase)
that are generated by signing a message with your private key.

This script uses py-clob-client to perform the derivation.

Usage:
    python scripts/derive_api_credentials.py

Prerequisites:
    - PRIVATE_KEY must be set in .env
    - py-clob-client must be installed
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.config import get_settings


def main() -> None:
    settings = get_settings()

    if not settings.private_key:
        print("ERROR: PRIVATE_KEY not set in .env")
        print("Set your wallet private key first, then re-run this script.")
        sys.exit(1)

    try:
        from py_clob_client.client import ClobClient
    except ImportError:
        print("ERROR: py-clob-client not installed.")
        print("Install with: pip install py-clob-client")
        sys.exit(1)

    print("Deriving API credentials...")
    print(f"  Host: {settings.polymarket_host}")
    print(f"  Chain ID: {settings.chain_id}")
    print()

    try:
        client = ClobClient(
            settings.polymarket_host,
            key=settings.private_key,
            chain_id=settings.chain_id,
        )
        creds = client.derive_api_key()

        print("Derived credentials (add these to your .env):")
        print()
        print(f'POLY_API_KEY={creds["apiKey"]}')
        print(f'POLY_API_SECRET={creds["secret"]}')
        print(f'POLY_PASSPHRASE={creds["passphrase"]}')
        print()
        print("WARNING: Keep these values secret. Never commit them to git.")

    except Exception as e:
        print(f"ERROR: Failed to derive credentials: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
